### ISSUE TITLE
List of plants

### ISSUE THREAD

**Issue by M-Bohmann** [M-Bohmann/Tourio-App#2]
## Value Proposition

**As a** user  
**I want to** view a list of insect friendly  balcony plants
**so that** i can decide which one i want to plant on my balcony
​

## Description

![Image](https://user-images.githubusercontent.com/131541143/247914648-0d70dc40-aec3-4672-8553-7f3c09c3ab8e.png)

## Acceptance Criteria

- [ ] user can see a list of plants
- [ ] list scrolls vertically
- [ ] heading always visible
      ​

## Tasks

- [ ] create branch
- [ ] create dummy data
- [ ] create a heading
- [ ] add basic styling
      ​

**Comment by julialoeschel** [comment]
Hey, 
super Story! 
nur eine Kleinigkeit: Ich würde bei Tasks noch aufführen, das du eine Card-Komponente erstellst. 

Ansonsten Super!

**Comment by julialoeschel** [comment]
💯
