### ISSUE TITLE
Plant filter

### ISSUE THREAD

**Issue by M-Bohmann** [M-Bohmann/Tourio-App#4]
## Value Proposition

**As a** user
**I want to** set my personal plant filter
**so that** i can get a list of plants according to my preferences
​

## Description

![Image](https://user-images.githubusercontent.com/131541143/248040638-78106a45-3bc2-42c9-8ad0-3cd76481d1aa.png)

​

## Acceptance Criteria

- [ ] user can specify their preferences in the form
- [ ] user can click a button to save their preferences
      ​

## Tasks

- [ ] create branch
- [ ] create save button
- [ ] create form component
- [ ] create heading
- [ ] add styling
      ​

**Comment by julialoeschel** [comment]
Hey, 
hier ist die Story noch nicht rund. 
der User speichert seine Einstellungen, aber wird denn auch gefiltert? 
hier fehlt mir noch die Anwendung der Filter auf die Daten, erst dann ist es eine Sinnvolle Story, die dem User einen Mehrwert schafft.

**Comment by julialoeschel** [comment]
🚀 
noch eine Idee dazu:
sollte dir die Story zu groß erscheinen, kannst du das scrollen als einzelne US auslagern.
