### ISSUE TITLE
balcony plant list

### ISSUE THREAD

**Issue by M-Bohmann** [M-Bohmann/Tourio-App#5]
## Value Proposition

**As a** user
**I want to** add plants from my filtered list to my personal balcony
**so that** I can plan my balcony plants
​

## Description

![Image](https://user-images.githubusercontent.com/131541143/248243135-da5ee3e8-d035-4450-8fd3-22e5d1c989f7.png)

​

## Acceptance Criteria

- [ ] user can add plants from the plant recommendations
- [ ] user can remove plants with a - button on the top right corner of an image at their balcony plant list
- [ ] user can see their selected balcony plants
- [ ] user can scroll vertically through their selected balcony plants
      ​

## Tasks

- [ ] create a branch
- [ ] create a plus button to add plants to the my balcony list
- [ ] create a minus button to remove plants from my balcony list
- [ ] create a heading Mein Balkon
- [ ] create a component​

**Comment by julialoeschel** [comment]
great !
a recommendation for the size: 
this could easily be 2 Userstories:
- one for creating the "Mein Balkon" component and adding Items and displaying them
- another one for the delete function.

this will reduce waiting time for a review and you have a highlight much faster by finishing a us quicker.
